name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 23.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: yarn install
      uses: borales/actions-yarn@v5
      with:
        cmd: install

    - name: yarn build
      uses: borales/actions-yarn@v5
      with:
        cmd: build

    - name: yarn lint
      uses: borales/actions-yarn@v5
      with:
        cmd: lint
